-- AlterEnum
ALTER TYPE "AssetStatus" ADD VALUE 'MAINTENANCE';
ALTER TYPE "AssetStatus" ADD VALUE 'DAMAGED';
ALTER TYPE "AssetStatus" ADD VALUE 'CRITICAL';
ALTER TYPE "AssetStatus" ADD VALUE 'LIKE_NEW';