import Head from 'next/head';
import Link from 'next/link';

/**
 * Public privacy policy page. Required for Google Play and App Store listings.
 * Customize the content for your organization and legal requirements.
 */
export default function PrivacyPage() {
  return (
    <>
      <Head>
        <title>Privacy Policy — AssetXAI</title>
        <meta name="description" content="AssetXAI Privacy Policy. How we collect, use, and protect your data." />
      </Head>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: 24, fontFamily: 'system-ui, sans-serif', color: '#1e293b', lineHeight: 1.6 }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ color: '#64748b', marginBottom: 32 }}>Last updated: {new Date().toLocaleDateString('en-US')}</p>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>1. Introduction</h2>
          <p>
            AssetXAI (&quot;we&quot;, &quot;our&quot;) provides asset management and tracking services via web and mobile applications.
            This policy describes how we collect, use, and protect your information when you use our services.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>2. Information we collect</h2>
          <p>
            We collect information you provide (e.g. account email, name, organization data) and data generated by your use of the app
            (e.g. asset records, locations, audit comments, tickets). Authentication is handled by Supabase; we do not store your password.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>3. How we use it</h2>
          <p>
            We use this information to provide and improve our services, enforce terms, and comply with law. We do not sell your personal data.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>4. Data security</h2>
          <p>
            We use industry-standard measures to protect your data. Access to the app is restricted to authenticated users and authorized roles.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>5. Contact</h2>
          <p>
            For privacy-related questions, contact your organization administrator or the support contact provided with your account.
          </p>
        </section>

        <p style={{ marginTop: 32 }}>
          <Link href="/login" style={{ color: '#4f46e5', fontWeight: 600 }}>← Back to login</Link>
        </p>
      </div>
    </>
  );
}
